TRAIN_URLS = {
    "COMPETITION": [  # --- 공모전 플랫폼 게시글 상세 페이지 (57건) ---
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110622",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110623",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110530",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110498",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110419",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110305",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110223",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21&gbn=view&gp=1&ix=110065",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=20&gbn=view&gp=1&ix=110585",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=20&gbn=view&gp=1&ix=110360",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=20&gbn=view&gp=1&ix=110273",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=20&gbn=view&gp=1&ix=110003",
        "https://www.wevity.com/?c=idea&s=1&gbn=viewok&gp=1&ix=109883",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030110001&str_no=202608250004",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=031610001&str_no=202608190008",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=031210001&str_no=202606260023",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030310001&str_no=202608290001",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030210001&str_no=202608280052",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=031210001&str_no=202608280033",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030110001&str_no=202608270058",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030610001&str_no=202608260046",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030310001&str_no=202608260004",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=031210001&str_no=202608240062",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=031410001&str_no=202608240060",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030910001&str_no=202608180055",
        "https://linkareer.com/activity/346834",
        "https://linkareer.com/activity/346824",
        "https://linkareer.com/activity/346807",
        "https://linkareer.com/activity/346797",
        "https://linkareer.com/activity/346791",
        "https://linkareer.com/activity/346776",
        "https://linkareer.com/activity/346770",
        "https://linkareer.com/activity/346720",
        "https://linkareer.com/activity/346703",
        "https://linkareer.com/activity/346685",
        "https://linkareer.com/activity/346675",
        "https://linkareer.com/activity/340455",
        "https://dacon.io/competitions/official/236756/overview",
        "https://dacon.io/competitions/official/236754/overview",
        "https://dacon.io/competitions/official/236753/overview",
        "https://dacon.io/competitions/official/236749/overview",
        "https://dacon.io/competitions/official/236746/overview",
        "https://dacon.io/competitions/official/236743/overview",
        "https://dacon.io/competitions/official/236727/overview",
        "https://dacon.io/competitions/official/236722/overview",
        "https://www.thinkcontest.com/thinkgood/user/outside/view.do?querystr=gpgXCwaRVhgtV7RtsEujJfxUicQEo9i1wO0m87raI1o",
        "https://www.thinkcontest.com/thinkgood/user/contest/view.do?querystr=gpgXCwaRVhgtV7RtsEujJQlSQbDuX9mZrsecXpAGGXC_lTR8Em_PTL3vSd1H8fOf",
        "https://www.thinkcontest.com/thinkgood/user/contest/view.do?querystr=gpgXCwaRVhgtV7RtsEujJYwoYmFklGtfbfNLsIEBAO6LPV-WbTIXsSVbLHBuF1t2",
        "https://www.thinkcontest.com/thinkgood/user/contest/view.do?querystr=gpgXCwaRVhgtV7RtsEujJcBUVWYNE59CzZJqYGaXk-c8TTjMKbDGWGlWwh8s5TJ6",
        "https://thinkyou.co.kr/contest/49663",
        "https://thinkyou.co.kr/contest/28863",
        "https://thinkyou.co.kr/contest/11534",
        "https://thinkyou.co.kr/contest/2058",
        "https://www.allforyoung.com/posts/63613",
        "https://www.allforyoung.com/posts/52754",
        "https://www.allforyoung.com/posts/32404",
        "https://www.allforyoung.com/posts/86773",
        # --- 시립대 공모전/팀활동 공지 페이지 (5건) ---
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA1&seq=31173&sort=5&pageIndex=1&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009002000000&identified=anonymous&",
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA1&seq=31307&sort=15&pageIndex=2&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009002000000&identified=anonymous&",
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA1&seq=31379&sort=26&pageIndex=3&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009002000000&identified=anonymous&",
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA1&seq=31302&sort=100&pageIndex=9&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009002000000&identified=anonymous&",
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA1&seq=31296&sort=57&pageIndex=5&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009002000000&identified=anonymous&",
        # --- 주최기관 공식 공모전 안내/접수 페이지 (8건) ---
        "https://aichallenge4all.or.kr/competitions/master100",
        "https://kobc.or.kr/ebz/kor/bbs/view.do?mId=0505010000&bIdx=98002&ptIdx=241",
        "https://www.sw.or.kr/site/sw/ex/board/View.do?cbIdx=292&bcIdx=66137&searchExt1=",
        "https://www.kshu.or.kr/bbs/board.php?code=campaign_07&bo_table=campaign_07",
        "https://pji.contestkorea.com/submission/regist_step1.php",
        "https://www.kamp-ai.kr/contestMain",
        "https://www.im-challenge.com/",
        "https://www.hybs.hnyouth.kr/0924%EC%98%81%EC%83%81%EC%A0%9C",
    ],
    "UNKNOWN": [  # --- 주최기관 홈페이지 (루트) (6건) ---
        "https://www.kobc.or.kr/",
        "https://www.sw.or.kr/",
        "https://www.mss.go.kr/",
        "https://www.kamp-ai.kr/",
        "https://aichallenge4all.or.kr/",
        "https://www.hybs.hnyouth.kr/",
        # --- 하드 네거티브 (공모전 주최기관 페이지 중 이미지만 있는 것) (1건) ---
        "https://www.xn--el3bt7o22a30rrlerj.com/123",
        # --- 하드 네거티브 (공모전 플랫폼 홈/목록 페이지) (14건) ---
        "https://www.wevity.com/",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=21",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=20",
        "https://www.wevity.com/?c=event&s=1&gub=1",
        "https://www.contestkorea.com/",
        "https://www.contestkorea.com/sub/list.php?displayrow=12&int_gbn=1&Txt_bcode=030510001",
        "https://www.thinkcontest.com/",
        "https://thinkyou.co.kr/",
        "https://thinkyou.co.kr/contest/",
        "https://www.allforyoung.com/posts/contest",
        "https://linkareer.com/list/contest",
        "https://dacon.io/competitions",
        "https://www.campuspick.com/contest",
        "https://www.detizen.com/",
    ],
    "NOT_COMPETITION": [
        # --- 시립대 홈/목록 페이지 (3건) ---
        "https://www.uos.ac.kr/kor/html/main.do",
        "https://www.uos.ac.kr/korNotice/list.do?list_id=FA34&menuid=2000005009004000000&identified=anonymous&",
        "https://www.uos.ac.kr/korNotice/list.do?list_id=FA1&menuid=2000005009002000000&identified=anonymous&",
        # --- 하드 네거티브 (시립대 공지 중 공모전/대회 형태가 아닌 것) (3건) ---
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA1&seq=31255&sort=2&pageIndex=1&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009002000000&identified=anonymous&",
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA1&seq=31363&sort=1&pageIndex=1&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009002000000&identified=anonymous&",
        "https://www.uos.ac.kr/korNotice/view.do?list_id=FA2&seq=9886&sort=51&pageIndex=5&searchCnd=&searchWrd=&cate_id=&viewAuth=Y&writeAuth=Y&board_list_num=10&lpageCount=12&menuid=2000005009003000000&identified=anonymous&",
        # --- 하드 네거티브 (채용/교육/기관 공지) (9건) ---
        "https://www.jobkorea.co.kr/",
        "https://www.saramin.co.kr/zf_user/",
        "https://www.wanted.co.kr/wdlist",
        "https://career.programmers.co.kr",
        "https://www.inflearn.com/",
        "https://www.coursera.org/browse",
        "https://www.k-mooc.kr/",
        "https://www.gov.kr/portal/main",
        "https://www.moe.go.kr/",
        # --- 일반 네거티브 (공모전 무관) (16건) ---
        "https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD",
        "https://namu.wiki/w/%ED%8C%8C%EC%9D%B4%EC%8D%AC",
        "https://github.com/torvalds/linux",
        "https://stackoverflow.com/questions",
        "https://developer.mozilla.org/ko/docs/Web/JavaScript",
        "https://docs.python.org/3/tutorial/index.html",
        "https://pytorch.org/get-started/locally/",
        "https://huggingface.co/docs/transformers/index",
        "https://arxiv.org/abs/1706.03762",
        "https://news.naver.com/",
        "https://www.hani.co.kr/",
        "https://www.bbc.com/korean",
        "https://www.coupang.com/",
        "https://www.musinsa.com/",
        "https://www.youtube.com/",
        "https://www.weather.go.kr/w/index.do",
    ],
}

TEST_URLS = {
    "COMPETITION": [  # --- 공모전 플랫폼 게시글 상세 페이지 (32건) ---
        "https://www.campuspick.com/contest/view?id=8887",
        "https://www.campuspick.com/contest/view?id=22961",
        "https://www.campuspick.com/contest/view?id=18872",
        "https://www.campuspick.com/contest/view?id=2407",
        "https://www.campuspick.com/contest/view?id=13645",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=1&gbn=view&gp=1&ix=110675",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=1&gbn=view&gp=1&ix=110635",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=19&gbn=view&gp=1&ix=110684",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=19&gbn=view&gp=1&ix=110599",
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=19&gbn=view&gp=1&ix=110591",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030210001&str_no=202609010064",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030210001&str_no=202608310026",
        "https://www.contestkorea.com/sub/view.php?int_gbn=1&Txt_bcode=030210001&str_no=202608310013",
        "https://linkareer.com/activity/347151",
        "https://linkareer.com/activity/347147",
        "https://dacon.io/competitions/official/236693/overview",
        "https://www.campuspick.com/activity/view?id=25430",
        "https://www.campuspick.com/activity/view?id=28396",
        "https://www.campuspick.com/activity/view?id=31626",
        "https://www.thinkcontest.com/Contest/ContestDetail.html?id=29240",
        "https://thinkyou.co.kr/contest/13750",
        "https://thinkyou.co.kr/contest/29418",
        "https://www.allforyoung.com/posts/84272",
        "https://onoffmix.com/event/342983",
        "https://onoffmix.com/event/341715",
        "https://onoffmix.com/event/325874",
        "https://event-us.kr/hancomedu/event/126525",
        "https://event-us.kr/twosuncampus/event/108454",
        "https://event-us.kr/xrplkorea/event/110761",
        "https://event-us.kr/icpkorea/event/80441",
        "https://www.kaggle.com/competitions/titanic",
        "https://www.kaggle.com/competitions/spaceship-titanic",
        # --- 주최기관 공식 공모전 안내 페이지 (3건) ---
        "http://gsia-sw.kr/main/index.html",
        "http://www.kidps.com/competition.php?gsp_pg=view&gsp_md=gb&gsp_gb_id=7&gsp_uid=21",
        "https://thinkyou.co.kr/contest/sector_view.asp?idx=12545",
    ],
    "UNKNOWN": [
        # --- 주최기관 홈페이지 (루트) (3건) ---
        "https://www.draju.com/",
        "https://www.law-lin.com/",
        "https://www.msit.go.kr/",
        # --- 공모전 플랫폼 홈/목록 페이지 (6건) ---
        "https://www.wevity.com/?c=find&s=1&gub=1&cidx=1",
        "https://www.contestkorea.com/sub/list.php?displayrow=12&int_gbn=1&Txt_bcode=030210001",
        "https://linkareer.com/list/contest?page=3",
        "https://www.campuspick.com/activity",
        "https://onoffmix.com/event",
        "https://event-us.kr/",
    ],
    "NOT_COMPETITION": [  # --- 하드 네거티브 (채용/교육) (5건) ---
        "https://www.albamon.com/",
        "https://www.incruit.com/",
        "https://www.jobplanet.co.kr/job",
        "https://www.udemy.com/ko/",
        "https://sll.seoul.go.kr/main/MainView.do",
        # --- 일반 네거티브 (공모전 무관) (6건) ---
        "https://www.gmarket.co.kr/",
        "https://realpython.com/",
        "https://ko.wikipedia.org/wiki/%EA%B8%B0%EA%B3%84_%ED%95%99%EC%8A%B5",
        "https://www.imbc.com/",
        "https://scikit-learn.org/stable/",
        "https://www.kma.go.kr/",
    ],
}
